# Generated by Django 6.0.1 on 2026-03-04 15:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("galeria", "0005_alter_fotografia_foto"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="fotografia",
            name="usuario",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fotos",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
